config/routes.rb
Rails.application.routes.draw do
  resources :art_types
  resources :emotions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root to: 'emotions#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/art_type.rb
class ArtType < ApplicationRecord
	belongs_to :emotion
end

app/models/emotion.rb
class Emotion < ApplicationRecord
	has_many :art_types

	def to_s
		titre
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/art_types_controller.rb
class ArtTypesController < ApplicationController
  before_action :set_art_type, only: [:show, :edit, :update, :destroy]

  # GET /art_types
  # GET /art_types.json
  def index
    @art_types = ArtType.all
  end

  # GET /art_types/1
  # GET /art_types/1.json
  def show
  end

  # GET /art_types/new
  def new
    @art_type = ArtType.new
  end

  # GET /art_types/1/edit
  def edit
  end

  # POST /art_types
  # POST /art_types.json
  def create
    @art_type = ArtType.new(art_type_params)

    respond_to do |format|
      if @art_type.save
        format.html { redirect_to @art_type, notice: 'Art type was successfully created.' }
        format.json { render :show, status: :created, location: @art_type }
      else
        format.html { render :new }
        format.json { render json: @art_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /art_types/1
  # PATCH/PUT /art_types/1.json
  def update
    respond_to do |format|
      if @art_type.update(art_type_params)
        format.html { redirect_to @art_type, notice: 'Art type was successfully updated.' }
        format.json { render :show, status: :ok, location: @art_type }
      else
        format.html { render :edit }
        format.json { render json: @art_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /art_types/1
  # DELETE /art_types/1.json
  def destroy
    @art_type.destroy
    respond_to do |format|
      format.html { redirect_to art_types_url, notice: 'Art type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_art_type
      @art_type = ArtType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def art_type_params
      params.require(:art_type).permit(:title, :date, :author, :interpreter, :dimention, :link, :emotion_id)
    end
end

app/controllers/emotions_controller.rb
class EmotionsController < ApplicationController
  before_action :set_emotion, only: [:show, :edit, :update, :destroy]

  # GET /emotions
  # GET /emotions.json
  def index
    @emotions = Emotion.all
  end

  # GET /emotions/1
  # GET /emotions/1.json
  def show
  end

  # GET /emotions/new
  def new
    @emotion = Emotion.new
  end

  # GET /emotions/1/edit
  def edit
  end

  # POST /emotions
  # POST /emotions.json
  def create
    @emotion = Emotion.new(emotion_params)

    respond_to do |format|
      if @emotion.save
        format.html { redirect_to @emotion, notice: 'Emotion was successfully created.' }
        format.json { render :show, status: :created, location: @emotion }
      else
        format.html { render :new }
        format.json { render json: @emotion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /emotions/1
  # PATCH/PUT /emotions/1.json
  def update
    respond_to do |format|
      if @emotion.update(emotion_params)
        format.html { redirect_to @emotion, notice: 'Emotion was successfully updated.' }
        format.json { render :show, status: :ok, location: @emotion }
      else
        format.html { render :edit }
        format.json { render json: @emotion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /emotions/1
  # DELETE /emotions/1.json
  def destroy
    @emotion.destroy
    respond_to do |format|
      format.html { redirect_to emotions_url, notice: 'Emotion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_emotion
      @emotion = Emotion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def emotion_params
      params.require(:emotion).permit(:titre, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/art_types_helper.rb
module ArtTypesHelper
end

app/helpers/emotions_helper.rb
module EmotionsHelper
end

app/views/art_types/_form.html.erb
<%= simple_form_for @art_type do |f| %>
  <%= f.input :title %>
  <%= f.input :date %>
  <%= f.input :author %>
  <%= f.input :interpreter %>
  <%= f.input :dimention %>
  <%= f.input :link %>
  <%= f.association :emotion %>
  <%= f.button :submit %>

<% end %>

app/views/art_types/edit.html.erb
<h1>Editing Art Type</h1>

<%= render 'form', art_type: @art_type %>

<%= link_to 'Show', @art_type %> |
<%= link_to 'Back', art_types_path %>

app/views/art_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Art Types</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>image</th>
      <th>Date</th>
      <th>Author</th>
      <th>Interpreter</th>
      <th>Dimention</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @art_types.each do |art_type| %>
      <tr>
        <td><%= art_type.title %></td>
        <td><img src="<%= art_type.link %>"></td>
        <td><%= art_type.date %></td>
        <td><%= art_type.author %></td>
        <td><%= art_type.interpreter %></td>
        <td><%= art_type.dimention %></td>
        <td><%= link_to 'Edit', edit_art_type_path(art_type) %></td>
        <td><%= link_to 'Destroy', art_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Back', emotions_path %>
<%= link_to 'New Art Type', new_art_type_path %>

app/views/art_types/new.html.erb
<h1>New Art Type</h1>

<%= render 'form', art_type: @art_type %>

<%= link_to 'Back', art_types_path %>

app/views/art_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @art_type.title %>
</p>

<p>
  <strong>Date:</strong>
  <%= @art_type.date %>
</p>

<p>
  <strong>Author:</strong>
  <%= @art_type.author %>
</p>

<p>
  <strong>Interpreter:</strong>
  <%= @art_type.interpreter %>
</p>

<p>
  <strong>Dimention:</strong>
  <%= @art_type.dimention %>
</p>

<%= link_to 'Edit', edit_art_type_path(@art_type) %> |
<%= link_to 'Back', art_types_path %>

app/views/emotions/_form.html.erb
<%= simple_form_for @emotion do |f| %>
  <%= f.input :titre %>
  <%= f.input :description %>
  <%= f.button :submit %>
<% end %>

app/views/emotions/edit.html.erb
<h1>Editing Emotion</h1>

<%= render 'form', emotion: @emotion %>

<%= link_to 'Show', @emotion %> |
<%= link_to 'Back', emotions_path %>

app/views/emotions/index.html.erb
<p id="notice"><%= notice %></p>
<link href="https://fonts.googleapis.com/css?family=Montserrat|Poppins:100,400&display=swap" rel="stylesheet">
<h1 class="title_expo">Expo temporaire : L'émotion dans l'art</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead></p>

  <tbody>

  </tbody>
</table>

<div class="container">
  <div class="row">
    <% @emotions.each do |emotion| %>
    <div class="col-md-6">
      <div class="card mb-4 shadow-sm">      
            <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Thumbnail"><title>emotion</title><rect width="100%" height="100%" fill="#55595c"></rect><text x="50%" y="50%" fill="#eceeef" dy=".3em"><%= emotion.titre %></text></svg>
            <div class="card-body">
              <blockquote class="blockquote text-center"><p class="card-text" class="mb-0"><%= emotion.description %></p></blockquote>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary"><%= link_to 'Show', emotion %></button>
                  <button type="button" class="btn btn-sm btn-outline-secondary"><%= link_to 'Edit', edit_emotion_path(emotion) %></button>
                  <button type="button" class="btn btn-sm btn-outline-secondary"><%= link_to 'Destroy', emotion, method: :delete, data: { confirm: 'Are you sure?' } %></button>
                </div>
                <small class="text-muted">9 mins</small>
              </div>
            </div>
      </div>      
    </div>
  <% end %>
  </div>
</div>     
<br>

<%= link_to 'New Emotion', new_emotion_path %>

app/views/emotions/new.html.erb
<h1>New Emotion</h1>

<%= render 'form', emotion: @emotion %>

<%= link_to 'Back', emotions_path %>

app/views/emotions/show.html.erb
<p id="notice"><%= notice %></p>

<p class="emotion_title">
  <strong>Titre:</strong>
  <%= @emotion.titre %>
</p>

<p>
  <strong>Description:</strong>
  <%= @emotion.description %>
</p>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>image</th>
      <th>Date</th>
      <th>Author</th>
      <th>Interpreter</th>
      <th>Dimention</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @emotion.art_types.each do |art_type| %>
      <tr>
        <td><%= art_type.title %></td>
        <td><img src="<%= art_type.link %>"></td>
        <td><%= art_type.date %></td>
        <td><%= art_type.author %></td>
        <td><%= art_type.interpreter %></td>
        <td><%= art_type.dimention %></td>
        <td><%= link_to 'Show', art_type %></td>
        <td><%= link_to 'Edit', edit_art_type_path(art_type) %></td>
        <td><%= link_to 'Destroy', art_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<%= link_to 'Edit', edit_emotion_path(@emotion) %> 
<%= link_to 'Back', emotions_path %>
<%= link_to 'New Art Type', new_art_type_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Museum</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>